#!/bin/bash
# ============================================================================
# load_guard.sh — machine-protection loop for the LPSN genus-coherence survey.
#
# WHY THIS EXISTS
#   On 2026-08-26 this host went down at ~17:18 local, roughly 10 minutes into a
#   140-thread DIAMOND run on Pseudomonas, and rebooted again at 17:32.
#   THE CAUSE WAS NOT ESTABLISHED. journalctl and /var/log/messages are root-only
#   for this account, so there is no readable OOM or panic record. Overload is a
#   HYPOTHESIS, not a finding, and nothing here should be read as saying otherwise.
#   This guard is a safety net asked for regardless of cause: if the machine ever
#   does get near the edge, it backs the survey off instead of hoping.
#
# WHAT IT DOES
#   Every 30s it samples 1-minute load average and available memory. If EITHER
#   threshold is breached on 3 CONSECUTIVE samples (~90s) it steps the survey's
#   thread count one rung down the ladder 96 -> 64 -> 48 -> 32, then kills the
#   DIAMOND search and the driver. scripts/watchdog.sh notices the dead driver
#   within 60s and restarts it, reading the new count from reports/THREADS.
#   This script NEVER starts the driver itself — that would race the watchdog and
#   risk two drivers.
#
#   It is a plain shell loop. No Python, no external dependency. It outlives
#   every session.
#
# WHY A TRIGGER MUST BE DELIBERATE (the 3-sample rule)
#   A DIAMOND search killed while running has NO checkpoint and starts from
#   scratch — pygemini's own documented behaviour (pygemini.py:687, restated in
#   HOW_TO_RESUME.md). On Pseudomonas that is hours. So a single spike must never
#   trigger; only a sustained breach may.
#
# THINGS THIS SCRIPT MUST NEVER DO (and does not)
#   - never passes --rerun-search  (it would delete a finished DIAMOND search)
#   - never deletes results/<Genus>/working/  (that IS the checkpoint)
#   - never writes or touches reports/survey_status.tsv  (that IS the resume point)
#   The only file it writes are reports/THREADS, its own log, pid and lock files.
#
# START:  setsid nohup bash scripts/load_guard.sh >/dev/null 2>&1 &
# STOP:   kill $(cat reports/load_guard.pid)
#         NOTE, verified 2026-08-26: a plain TERM can take up to SAMPLE_INTERVAL
#         (30s) to take effect. bash defers a trapped signal until the foreground
#         command - here the 30s sleep - has finished. It then logs 'load_guard
#         STOP' and releases the lock. Wait for that STOP line before starting a
#         replacement, or the replacement will correctly refuse with 'another
#         load_guard holds the lock'. Do NOT edit this file until STOP has appeared.
# ============================================================================

set -u
# Every file this script creates (log, pid, lock, THREADS temp) must be owner-only.
umask 077

S=/data/prosjekt/15719-Res-Marine/Project_Work/Project_Pygemini/LPSN_Genus_Survey
R="$S/reports"
LOG="$R/load_guard.log"
THREADS_FILE="$R/THREADS"
LOCK="$R/load_guard.lock"
PIDFILE="$R/load_guard.pid"

# ---------------------------------------------------------------------------
# THRESHOLDS — the two numbers that decide everything. Change them here only.
# ---------------------------------------------------------------------------

# 1-minute load average above which we consider the machine over-committed.
# This host has 256 cores (nproc = 256), so load 256 is "every core busy with
# nothing waiting". 230 is ~90% of that: high enough that ordinary healthy work
# at 96 DIAMOND threads (observed load ~50-100) never approaches it, low enough
# to leave ~26 cores of slack before the run queue is genuinely saturated.
LOAD1_MAX=230

# Available memory (GB) below which we consider memory pressure real.
# The host has 1006 GB total and reported 974 GB available with the 96-thread
# DIAMOND running. 80 GB is ~8% of total: by the time only 80 GB is left,
# something has consumed more than 900 GB and the kernel is close to reclaiming
# or OOM-killing. MemAvailable is used (not "free"), so page cache does not
# count against us.
MEM_AVAIL_MIN_GB=80

# ---------------------------------------------------------------------------
# TIMING
# ---------------------------------------------------------------------------
SAMPLE_INTERVAL=30          # seconds between samples
BREACH_SAMPLES_REQUIRED=3   # consecutive breached samples before acting (~90s)
COOLDOWN_SECONDS=900        # 15 min after a trigger before it may trigger again,
                            # so the restarted run has time to establish itself
FLOOR_ALERT_INTERVAL=900    # at the floor, re-log the alert at most this often
FLAP_LOG_MIN_INTERVAL=300   # do not re-log "breach started" more often than this
HEARTBEAT_SECONDS=21600     # 6 h "still alive" line, so silence is not ambiguous

# ---------------------------------------------------------------------------
# THREAD LADDER — descending. Matches the count already in use (96) and the
# rungs sanctioned for stepping down. 32 is the floor.
# ---------------------------------------------------------------------------
LADDER="96 64 48 32"
LADDER_FLOOR=32

# Pattern that identifies the survey's DIAMOND search. Matched against the full
# command line. NOTE: the driver spells its paths /data/prosjekt/... while the
# DIAMOND child spells the same directory /gpfs/gpfs0/prosjekt/.prosjekt2/... —
# same filesystem, two mount spellings. Matching on the directory NAME rather
# than on either absolute path is what makes this pattern work for both.
DIAMOND_PATTERN='diamond blastp.*LPSN_Genus_Survey'
RUNFAST_PATTERN='run_fast\.py.*LPSN_Genus_Survey'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log(){ echo "$(date -u +%FT%TZ) $*" >> "$LOG"; }

# Sampling. Both are one-liners on purpose: the ladder test overrides them.
sample_load1(){ awk '{print $1}' /proc/loadavg 2>/dev/null; }
sample_mem_avail_gb(){ awk '/^MemAvailable:/{printf "%d", int($2/1048576)}' /proc/meminfo 2>/dev/null; }

# load1 is a float; integer test would be wrong. Compare in awk.
load_over(){ awk -v l="$1" -v m="$2" 'BEGIN{exit !(l+0 > m+0)}'; }

read_threads(){
  local t
  t=$(cat "$THREADS_FILE" 2>/dev/null)
  case "$t" in ''|*[!0-9]*) t=$LADDER_FLOOR ;; esac   # unreadable/garbage: assume floor,
  echo "$t"                                          # i.e. fail safe, never step UP
}

# Atomic: temp file in the same directory, then mv. A reader (watchdog) can never
# see a half-written or empty THREADS file.
write_threads(){
  local new="$1" tmp
  tmp="$(mktemp "$R/.THREADS.XXXXXX")" || return 1
  printf '%s\n' "$new" > "$tmp" && chmod 600 "$tmp" && mv -f "$tmp" "$THREADS_FILE"
}

# Largest ladder rung strictly below $1. Empty output means "already at or below
# the floor". A current value not on the ladder (e.g. 140) still steps correctly.
next_threads(){
  local cur="$1" v
  for v in $LADDER; do
    if [ "$v" -lt "$cur" ]; then echo "$v"; return 0; fi
  done
  echo ""
}

# TERM, give it 10s, then KILL. Returns the pids it acted on.
kill_diamond(){
  local pids p
  pids=$(pgrep -u "$(id -u)" -f "$DIAMOND_PATTERN" 2>/dev/null | tr '\n' ' ')
  if [ -z "$pids" ]; then log "  kill_diamond: no DIAMOND process matched — nothing to kill"; return 0; fi
  log "  kill_diamond: TERM $pids"
  kill $pids 2>/dev/null
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    pgrep -u "$(id -u)" -f "$DIAMOND_PATTERN" >/dev/null 2>&1 || break
    sleep 1 9>&-
  done
  for p in $(pgrep -u "$(id -u)" -f "$DIAMOND_PATTERN" 2>/dev/null); do
    log "  kill_diamond: still alive after 10s — KILL $p"; kill -9 "$p" 2>/dev/null
  done
}

kill_driver(){
  local p
  p=$(cat "$R/driver.pid" 2>/dev/null)
  case "$p" in ''|*[!0-9]*) log "  kill_driver: no usable driver.pid — nothing to kill"; return 0 ;; esac
  if ! kill -0 "$p" 2>/dev/null; then log "  kill_driver: driver pid=$p already gone"; return 0; fi
  log "  kill_driver: TERM $p"
  kill "$p" 2>/dev/null
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    kill -0 "$p" 2>/dev/null || break
    sleep 1 9>&-
  done
  if kill -0 "$p" 2>/dev/null; then
    log "  kill_driver: still alive after 10s — KILL $p"; kill -9 "$p" 2>/dev/null
  fi
  # The driver holds reports/driver.lock. If it lingered, the watchdog's restart
  # would exit with "another driver holds the lock" and the survey would stall.
  # Hence the escalation above is not optional.
  #
  # The driver runs DIAMOND through an intermediate AAI_Optimisation/run_fast.py.
  # Killing DIAMOND normally makes run_fast.py fail out on its own, but if it is
  # still there after the driver is gone it is an orphan holding nothing useful,
  # so sweep it. (This step is an addition to the literal "DIAMOND then driver"
  # instruction; it is here because an orphaned run_fast.py could otherwise sit
  # in the process table and confuse the next diagnosis.)
  local orph
  orph=$(pgrep -u "$(id -u)" -f "$RUNFAST_PATTERN" 2>/dev/null | tr '\n' ' ')
  if [ -n "$orph" ]; then log "  kill_driver: sweeping orphaned run_fast.py $orph"; kill $orph 2>/dev/null; fi
}

# ---------------------------------------------------------------------------
# One step down the ladder. This is the whole "action" path, in one function,
# so it can be exercised in isolation (see the ladder test in the session record:
# the test sources this file, stubs kill_diamond/kill_driver with echo, points
# THREADS_FILE at a temp file, and calls step_down repeatedly).
# Returns 0 if it stepped, 1 if it was already at the floor.
# ---------------------------------------------------------------------------
step_down(){
  local cur new
  cur=$(read_threads)
  new=$(next_threads "$cur")

  if [ -z "$new" ]; then
    # AT THE FLOOR (32). Deliberately do NOT kill anything here.
    # Reasoning: every trigger destroys an in-progress DIAMOND search that has no
    # checkpoint, and buys back capacity only if there is a lower rung to move to.
    # At 32 threads there is nothing left to give — killing would throw away hours
    # of search and restart at the same 32 threads, i.e. pure loss. If the machine
    # is still in trouble at 32 threads the cause is almost certainly NOT this
    # survey, and a human needs to look. So: shout in the log, keep watching.
    log "ALERT ***********************************************************"
    log "ALERT AT LADDER FLOOR ($cur threads) AND STILL BREACHING."
    log "ALERT Not killing anything: there is no lower rung, so a kill would"
    log "ALERT destroy an uncheckpointed DIAMOND search for zero benefit."
    log "ALERT This needs a human. Check what else is on the machine (ps, uptime)."
    log "ALERT ***********************************************************"
    return 1
  fi

  log "ACTION STEP-DOWN $cur -> $new threads (sustained breach)"
  if write_threads "$new"; then
    log "  reports/THREADS written atomically: $(cat "$THREADS_FILE" 2>/dev/null)"
  else
    log "  ERROR could not write reports/THREADS — aborting step-down, killing nothing"
    return 1
  fi
  kill_diamond
  kill_driver
  log "ACTION kills issued. Not restarting the driver — scripts/watchdog.sh will"
  log "  notice within 60s and restart it at -t $new from reports/THREADS."
  log "  The DIAMOND search restarts from scratch (no checkpoint); that cost is known."
  return 0
}

# ---------------------------------------------------------------------------
# When this file is SOURCED rather than executed, stop here: definitions only,
# no lock, no loop. That is how the ladder logic is tested without touching the
# live run.
# ---------------------------------------------------------------------------
[ "${BASH_SOURCE[0]}" != "${0}" ] && return 0

cd "$S" || exit 1

# ---------------------------------------------------------------------------
# Single instance, via flock on fd 9.
#
# THE INHERITED-FD BUG WE ARE IMMUNE TO (it bit watchdog.sh on 2026-08-26):
# a child process inherits open file descriptors, INCLUDING the flock fd. When
# watchdog.sh was killed while inside `sleep 60`, the orphaned sleep kept fd 9
# open, so the kernel kept the lock held for up to 60 more seconds and the
# replacement watchdog exited with "another watchdog holds the lock".
#
# THE FIX HERE: every command that can outlive a signal — i.e. every `sleep` —
# is invoked with `9>&-`, which closes fd 9 in that child only. No child ever
# holds the lock, so the moment this process dies (even by SIGKILL, where no
# trap can run) the last reference to the fd is gone and the lock is released
# immediately. A replacement guard can start the same second.
# The EXIT/TERM/INT trap below is belt-and-braces for the graceful cases.
# ---------------------------------------------------------------------------
exec 9>"$LOCK"
if ! flock -n 9; then
  log "another load_guard holds the lock; exiting (pid=$$)"
  exit 0
fi
echo $$ > "$PIDFILE"
chmod 600 "$PIDFILE" 2>/dev/null

# One cleanup, one trap, guarded against running twice (a TERM handler that
# exits would otherwise re-enter it via the EXIT trap and log STOP twice).
_cleaned=0
cleanup(){ [ "$_cleaned" = 1 ] && return 0; _cleaned=1
           log "load_guard STOP pid=$$"; flock -u 9 2>/dev/null; exec 9>&- 2>/dev/null; }
# TERM/INT must cleanup AND exit — a bare trap handler returns into the loop.
trap 'cleanup; exit 0' TERM INT
trap 'cleanup' EXIT

log "load_guard START pid=$$ thresholds: load1>$LOAD1_MAX OR memavail<${MEM_AVAIL_MIN_GB}GB, \
sustained ${BREACH_SAMPLES_REQUIRED}x${SAMPLE_INTERVAL}s, ladder=[$LADDER], cooldown=${COOLDOWN_SECONDS}s"
log "load_guard initial state: threads=$(read_threads) load1=$(sample_load1) memavail=$(sample_mem_avail_gb)GB"

breach_count=0
begin_logged=0
suppressed_begins=0
last_begin_log=0
cooldown_until=0
last_heartbeat=$(date +%s)

while true; do
  now=$(date +%s)
  load1=$(sample_load1)
  memgb=$(sample_mem_avail_gb)

  # Defensive: if /proc could not be read, do nothing this round rather than
  # guessing. Never act on a missing measurement.
  if [ -z "${load1:-}" ] || [ -z "${memgb:-}" ]; then
    log "WARN could not sample /proc (load1='${load1:-}' memavail='${memgb:-}') — skipping this round"
    sleep "$SAMPLE_INTERVAL" 9>&-
    continue
  fi

  breached=0
  reason=""
  if load_over "$load1" "$LOAD1_MAX"; then breached=1; reason="load1=$load1 > $LOAD1_MAX"; fi
  if [ "$memgb" -lt "$MEM_AVAIL_MIN_GB" ]; then
    breached=1
    [ -n "$reason" ] && reason="$reason AND " 
    reason="${reason}memavail=${memgb}GB < ${MEM_AVAIL_MIN_GB}GB"
  fi

  if [ "$breached" -eq 1 ]; then
    breach_count=$((breach_count + 1))

    # State change: a breach run has begun. Log it — but throttled, so a load
    # oscillating around the threshold cannot fill the log with begin/clear pairs.
    if [ "$breach_count" -eq 1 ]; then
      if [ $((now - last_begin_log)) -ge "$FLAP_LOG_MIN_INTERVAL" ]; then
        log "WARN threshold breached ($reason) — sample 1/$BREACH_SAMPLES_REQUIRED, watching"
        [ "$suppressed_begins" -gt 0 ] && log "  ($suppressed_begins earlier short breaches not logged — threshold is being grazed)"
        suppressed_begins=0
        last_begin_log=$now
        begin_logged=1
      else
        suppressed_begins=$((suppressed_begins + 1))
        begin_logged=0
      fi
    fi

    if [ "$breach_count" -ge "$BREACH_SAMPLES_REQUIRED" ]; then
      if [ "$now" -lt "$cooldown_until" ]; then
        # Sustained breach, but we acted recently. Do not act again yet.
        if [ "$breach_count" -eq "$BREACH_SAMPLES_REQUIRED" ]; then
          log "WARN sustained breach ($reason) but in cooldown for $((cooldown_until - now))s more — not acting"
        fi
      else
        log "TRIGGER sustained breach over $((breach_count * SAMPLE_INTERVAL))s: $reason"
        log "  load1=$load1 memavail=${memgb}GB threads=$(read_threads)"
        if step_down; then
          cooldown_until=$((now + COOLDOWN_SECONDS))
          log "  cooldown until $(date -u -d "@$cooldown_until" +%FT%TZ) (${COOLDOWN_SECONDS}s)"
        else
          # Floor, or a failed write. Re-arm, but rate-limit the alert.
          cooldown_until=$((now + FLOOR_ALERT_INTERVAL))
        fi
        breach_count=0
        begin_logged=0
      fi
    fi
  else
    if [ "$breach_count" -gt 0 ]; then
      [ "$begin_logged" -eq 1 ] && \
        log "INFO breach cleared after $breach_count sample(s) (~$((breach_count * SAMPLE_INTERVAL))s) — load1=$load1 memavail=${memgb}GB"
      breach_count=0
      begin_logged=0
    fi
  fi

  # Low-frequency proof of life, so a silent log is unambiguous.
  if [ $((now - last_heartbeat)) -ge "$HEARTBEAT_SECONDS" ]; then
    log "INFO alive — load1=$load1 memavail=${memgb}GB threads=$(read_threads) (heartbeat, every $((HEARTBEAT_SECONDS/3600))h)"
    last_heartbeat=$now
  fi

  # `9>&-` closes the lock fd in the sleep child. See the lock comment above.
  sleep "$SAMPLE_INTERVAL" 9>&-
done
